### ISSUE TITLE
Add phppgadmin for postgres web administration

### ISSUE THREAD

**Issue by astronaute77** [amaia/rails-starter-box#1]
Hey, this box has almost everything needed for application development even ImageMagick!
I usually like to edit DB via web administration phppgadmin, do you think this is something you can add through puppet?

Thank you :)

**Comment by amaia** [comment]
Hey, sorry for the late response, I'll look into it, thanks for the suggestion @astronaute

**Comment by emil-nasso** [comment]
I would love to see this feature too! :+1:
