### ISSUE TITLE
How to sync host rails project to vagrant box .

### ISSUE THREAD

**Issue by xiaods** [amaia/rails-starter-box#2]
you suggest workflow:
The recommended workflow is
- edit files in the host computer
- run within the virtual machine

but I am not found any way to sync project to vagrant box. please hint me. thanks a lot.

**Comment by emil-nasso** [comment]
You should take a look at this:
http://docs.vagrantup.com/v1/docs/config/vm/share_folder.html

With shared folders you can mount an directory from your local machine to the virtual machine. 

Or you could put everything in the folder you get when you clone this repository. Everything in that folder is mounted in /vagrant on the virtual machine.

**Comment by xiaods** [comment]
cool. that my need info.thanks a lot. @emil-nasso
