### ISSUE TITLE
Ruby 2.0 support?

### ISSUE THREAD

**Issue by pcriv** [amaia/rails-starter-box#5]
Does this box install ruby 2.0.0?

**Comment by OhMyMndy** [comment]
On the VM with `vagrant ssh`,  `ruby --version` returns `ruby 1.8.7 (2012-02-08 patchlevel 358) [i686-linux]`
Maybe you could try to update to Ruby 2.0?

**Comment by pcriv** [comment]
i created my own vagrant config based on this repo and rails-dev-box repo.
Currently i commented MySQL instaltion because it was failing (puppet package error).
It works well for development and testing. 
Give it a try if you want.
https://github.com/pablocrivella/railsapps-dev-box
